import { create } from 'zustand';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Message, ChatSession, SessionEnvironment, WorkspaceFile, SwarmSession } from '../types';
import { useMeshStore } from './useMeshStore';
import { useSwarmStore, registerSwarmListeners } from './useSwarmStore';
import { evaluateSwarmNeed } from '../services/swarmService';
import { streamChatCompletion } from '../services/vllmService';
import {
  extractFilesFromMarkdown,
  downloadEnvironmentAsZip,
} from '../services/zipService';
import { telemetryBridge } from '../services/matrix/TelemetryStreamBridge';
import { evaluateFactualGrounding } from '../services/hallucinationDetector';
import { useRagStore } from './useRagStore';
import {
  markFileDirty,
  markFileDeleted,
  markEnvReplaceAll,
  markEnvAllDirty,
} from '../services/sandboxDirty';

const STORAGE_KEY = '@spark_chat_vault_v3';

interface ChatState {
  sessions: ChatSession[];
  activeSessionId: string | null;
  messages: Record<string, Message[]>;
  environments: Record<string, SessionEnvironment>;
  isStreaming: boolean;
  activeAbortController: AbortController | null;
  antiHallucination: boolean;

  // Actions
  createNewSession: (initialTitle?: string) => string;
  selectSession: (id: string) => void;
  deleteSession: (id: string) => void;
  clearCurrentSession: () => void;
  sendMessage: (text: string) => Promise<void>;
  stopStreaming: () => void;
  loadFromStorage: () => Promise<void>;
  saveToStorage: () => Promise<void>;
  toggleAntiHallucination: () => void;
  setAntiHallucination: (enabled: boolean) => void;
  updateLastAssistantMessageSwarm: (swarm: SwarmSession) => void;

  // Environment Actions
  getActiveEnvironment: () => SessionEnvironment | null;
  addOrUpdateFile: (
    envId: string,
    path: string,
    content: string,
    language?: string
  ) => void;
  addOrUpdateFiles: (
    envId: string,
    files: { path: string; content: string; language?: string }[]
  ) => void;
  removeFile: (envId: string, path: string) => void;
  clearEnvironment: (envId: string) => void;
  downloadActiveEnvironmentZip: () => void;
  flushSave: () => Promise<void>;
}

let saveTimer: ReturnType<typeof setTimeout> | null = null;
let persistDirty = false;

function scheduleSave() {
  persistDirty = true;
  if (saveTimer) return;
  saveTimer = setTimeout(() => {
    saveTimer = null;
    void useChatStore.getState().saveToStorage();
  }, 400);
}

function createInitialEnvironment(sessionId: string): SessionEnvironment {
  const shortSlug = sessionId.replace('session_', '').slice(-4) || 'init';
  const envId = `env_${sessionId.replace('session_', '')}`;
  return {
    id: envId,
    sessionId,
    name: `sandbox-${shortSlug}`,
    files: {
      'README.md': {
        path: 'README.md',
        content: `# Workspace Sandbox (${envId})\n\nDedicated temporary environment for this conversation.\nAny code blocks or files generated by Sovereign Spark will automatically sync here.\nUse the 'Download ZIP' button to export this entire sandbox to your local machine.\n`,
        language: 'markdown',
        updatedAt: Date.now(),
        sizeBytes: 245,
      },
    },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };
}

export const useChatStore = create<ChatState>((set, get) => ({
  sessions: [],
  activeSessionId: null,
  messages: {},
  environments: {},
  isStreaming: false,
  activeAbortController: null,
  antiHallucination: true,

  toggleAntiHallucination: () => {
    set((state) => ({ antiHallucination: !state.antiHallucination }));
  },

  setAntiHallucination: (enabled: boolean) => {
    set({ antiHallucination: enabled });
  },

  updateLastAssistantMessageSwarm: (swarm: SwarmSession) => {
    const { activeSessionId, messages } = get();
    if (!activeSessionId) return;
    const sessionMsgs = [...(messages[activeSessionId] || [])];
    const lastIdx = sessionMsgs.length - 1;
    if (lastIdx >= 0 && sessionMsgs[lastIdx].role === 'assistant') {
      sessionMsgs[lastIdx] = {
        ...sessionMsgs[lastIdx],
        swarmSession: swarm,
      };
      set({
        messages: {
          ...messages,
          [activeSessionId]: sessionMsgs,
        },
      });
    }
  },

  getActiveEnvironment: () => {
    const { sessions, activeSessionId, environments } = get();
    if (!activeSessionId) return null;
    const session = sessions.find((s) => s.id === activeSessionId);
    if (!session || !session.envId) return null;
    return environments[session.envId] || null;
  },

  createNewSession: (initialTitle = 'New Conversation') => {
    const newId = 'session_' + Date.now();
    const newEnv = createInitialEnvironment(newId);

    const newSession: ChatSession = {
      id: newId,
      title: initialTitle,
      envId: newEnv.id,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    };

    set((state) => ({
      sessions: [newSession, ...state.sessions],
      environments: { ...state.environments, [newEnv.id]: newEnv },
      activeSessionId: newId,
      messages: { ...state.messages, [newId]: [] },
    }));

    markEnvAllDirty(newEnv.id, Object.keys(newEnv.files));
    void get().flushSave();
    return newId;
  },

  selectSession: (id: string) => {
    void get().flushSave();
    set({ activeSessionId: id });
  },

  deleteSession: (id: string) => {
    set((state) => {
      const targetSession = state.sessions.find((s) => s.id === id);
      const remainingSessions = state.sessions.filter((s) => s.id !== id);
      const remainingMessages = { ...state.messages };
      delete remainingMessages[id];

      const remainingEnvironments = { ...state.environments };
      if (targetSession?.envId) {
        delete remainingEnvironments[targetSession.envId];
      }

      const nextActiveId =
        state.activeSessionId === id
          ? remainingSessions.length > 0
            ? remainingSessions[0].id
            : null
          : state.activeSessionId;

      return {
        sessions: remainingSessions,
        activeSessionId: nextActiveId,
        messages: remainingMessages,
        environments: remainingEnvironments,
      };
    });
    void get().flushSave();
  },

  clearCurrentSession: () => {
    const activeId = get().activeSessionId;
    if (!activeId) return;

    set((state) => ({
      messages: {
        ...state.messages,
        [activeId]: [],
      },
    }));
    scheduleSave();
  },

  addOrUpdateFile: (
    envId: string,
    path: string,
    content: string,
    language?: string
  ) => {
    get().addOrUpdateFiles(envId, [{ path, content, language }]);
  },

  addOrUpdateFiles: (
    envId: string,
    files: { path: string; content: string; language?: string }[]
  ) => {
    if (!files.length) return;
    set((state) => {
      const targetEnv = state.environments[envId];
      if (!targetEnv) return state;

      const nextFiles = { ...targetEnv.files };
      const now = Date.now();
      for (const f of files) {
        nextFiles[f.path] = {
          path: f.path,
          content: f.content,
          language: f.language || 'text',
          updatedAt: now,
          sizeBytes: new TextEncoder().encode(f.content).length,
        };
        markFileDirty(envId, f.path);
      }

      return {
        environments: {
          ...state.environments,
          [envId]: {
            ...targetEnv,
            files: nextFiles,
            updatedAt: now,
          },
        },
      };
    });
    scheduleSave();
  },

  removeFile: (envId: string, path: string) => {
    set((state) => {
      const targetEnv = state.environments[envId];
      if (!targetEnv) return state;

      const updatedFiles = { ...targetEnv.files };
      delete updatedFiles[path];

      return {
        environments: {
          ...state.environments,
          [envId]: {
            ...targetEnv,
            files: updatedFiles,
            updatedAt: Date.now(),
          },
        },
      };
    });
    markFileDeleted(envId, path);
    scheduleSave();
  },

  clearEnvironment: (envId: string) => {
    set((state) => {
      const targetEnv = state.environments[envId];
      if (!targetEnv) return state;

      return {
        environments: {
          ...state.environments,
          [envId]: {
            ...targetEnv,
            files: {},
            updatedAt: Date.now(),
          },
        },
      };
    });
    markEnvReplaceAll(envId);
    scheduleSave();
  },

  downloadActiveEnvironmentZip: () => {
    const activeEnv = get().getActiveEnvironment();
    if (activeEnv) {
      downloadEnvironmentAsZip(activeEnv);
    }
  },

  sendMessage: async (text: string) => {
    if (!text.trim() || get().isStreaming) return;

    let currentSessionId = get().activeSessionId;
    if (!currentSessionId) {
      currentSessionId = get().createNewSession(
        text.slice(0, 28) + (text.length > 28 ? '...' : '')
      );
    } else {
      // Update session title if first user message
      const existing = get().messages[currentSessionId] || [];
      if (existing.length === 0) {
        set((state) => ({
          sessions: state.sessions.map((s) =>
            s.id === currentSessionId
              ? {
                  ...s,
                  title:
                    text.slice(0, 28) + (text.length > 28 ? '...' : ''),
                  updatedAt: Date.now(),
                }
              : s
          ),
        }));
      }
    }

    const currentSession = get().sessions.find((s) => s.id === currentSessionId);
    const activeEnv = currentSession?.envId
      ? get().environments[currentSession.envId]
      : null;
    const envDisplayName = activeEnv?.name || 'sandbox';

    const userMsg: Message = {
      id: 'msg_' + Date.now(),
      role: 'user',
      content: text.trim(),
      timestamp: Date.now(),
    };

    const assistantMsgId = 'msg_' + (Date.now() + 1);
    const assistantMsg: Message = {
      id: assistantMsgId,
      role: 'assistant',
      content: '',
      reasoning: '',
      timestamp: Date.now(),
    };

    const controller = new AbortController();

    set((state) => ({
      isStreaming: true,
      activeAbortController: controller,
      messages: {
        ...state.messages,
        [currentSessionId!]: [
          ...(state.messages[currentSessionId!] || []),
          userMsg,
          assistantMsg,
        ],
      },
    }));

    try {
      const activeHost = useMeshStore.getState().activeHost;
      const activePort = useMeshStore.getState().activePort;

      // Check if Multi-Agent Swarm Mode is active
      const isSwarmMode = useSwarmStore.getState().isSwarmMode;
      let shouldSpawnSwarm = false;
      let swarmDecisionReason = '';

      if (isSwarmMode && activeEnv) {
        // Agent autonomously evaluates if task warrants spawning a multi-agent swarm
        const evaluation = await evaluateSwarmNeed({
          prompt: text,
          activeFileCount: Object.keys(activeEnv.files).length,
          host: activeHost,
          port: activePort,
        });

        shouldSpawnSwarm = evaluation.shouldSpawn;
        swarmDecisionReason = evaluation.reason;
      }

      if (shouldSpawnSwarm && activeEnv) {
        const swarm = await useSwarmStore.getState().startSwarmTask(
          text,
          currentSessionId!,
          activeEnv.id,
          activeEnv.files,
          swarmDecisionReason
        );

        if (swarm) {
          const taskSummary = swarm.tasks
            .map(
              (t) =>
                `- **${t.title}** (${t.role.toUpperCase()}): \`${t.targetFiles.join(', ')}\` [${t.status.toUpperCase()}]`
            )
            .join('\n');

          const finalSummary = `### Multi-Agent Swarm Execution Complete\n\nAll specialized workers finished and synchronized into the **${envDisplayName}** sandbox environment.\n\n*Agent Decision: ${swarm.dispatchReason || swarmDecisionReason || 'Complex project decomposed across parallel subagents'}*\n\n${taskSummary}\n\nAutomated test matrix executed in ephemeral sandbox.`;

          set((state) => {
            const sessionMsgs = [
              ...(state.messages[currentSessionId!] || []),
            ];
            const lastIdx = sessionMsgs.findIndex(
              (m) => m.id === assistantMsgId
            );
            if (lastIdx !== -1) {
              sessionMsgs[lastIdx] = {
                ...sessionMsgs[lastIdx],
                content: finalSummary,
                swarmSession: swarm,
              };
            }
            return {
              messages: {
                ...state.messages,
                [currentSessionId!]: sessionMsgs,
              },
              isStreaming: false,
              activeAbortController: null,
            };
          });
          void get().flushSave();
          return;
        }
      }

      const messageHistory = (get().messages[currentSessionId!] || [])
        .filter((m) => m.id !== assistantMsgId)
        .map((m) => ({ role: m.role, content: m.content }));

      let accumulatedContent = '';
      let accumulatedReasoning = isSwarmMode && swarmDecisionReason
        ? `[Swarm Triage: Single Agent — ${swarmDecisionReason}]\n\n`
        : '';
      let lastUpdateTime = 0;

      const isAntiHallucination = get().antiHallucination;
      const existingFiles = activeEnv ? Object.keys(activeEnv.files) : [];
      const activeFilesSummary = existingFiles.length > 0
        ? existingFiles.map((f) => `  - ${f} (${activeEnv!.files[f].language || 'text'}, ${activeEnv!.files[f].sizeBytes || 0} bytes)`).join('\n')
        : '  (No files created yet in sandbox)';

      const ragState = useRagStore.getState();
      let ragContext = '';
      let ragCitations: ReturnType<typeof ragState.contextForQuery>['citations'] = [];
      if (ragState.enabled) {
        try {
          ragState.ingestEnvironment(activeEnv);
          const retrieved = ragState.contextForQuery(text.trim(), 6);
          ragContext = retrieved.context;
          ragCitations = retrieved.citations;
        } catch (e) {
          console.warn('[chat] RAG retrieve failed:', e);
        }
      }

      // When RAG is off, inject truncated file dumps. When RAG is on, retrieved chunks replace the dump.
      const activeFilesContext = ragState.enabled
        ? ''
        : existingFiles.length > 0
        ? existingFiles.map((f) => {
            const file = activeEnv!.files[f];
            if (!file?.content) return '';
            const snippet = file.content.length > 8000
              ? file.content.slice(0, 8000) + '\n... [Content truncated for length]'
              : file.content;
            return `========================================\nFILE: ${f} (${file.language || 'text'})\n========================================\n${snippet}\n========================================`;
          }).filter(Boolean).join('\n\n')
        : '';

      const ragSection = ragContext
        ? `
RETRIEVED LOCAL KNOWLEDGE (hybrid BM25 + dense; treat as source of truth):
${ragContext}

Citation rules: quote or paraphrase only from the numbered passages above. If they do not contain the answer, say you do not have that fact in the local index rather than inventing it.
`
        : ragState.enabled
        ? `
LOCAL RAG is enabled but retrieved no passages for this query. Do not invent cluster facts, APIs, or file contents. Say the local index does not contain the answer.
`
        : '';

      const antiHallucinationSection = isAntiHallucination ? `
CRITICAL ZERO-HALLUCINATION & FACTUAL GROUNDING PROTOCOL [ACTIVE]:
You are strictly anchored to empirical truth, verified standard libraries, and concrete sandbox files.
Confabulation, guessing, and synthetic hallucination are strictly prohibited.

1. ABSOLUTE FACTUALITY & CODE VERIFICATION:
   - NEVER fabricate or invent Python/Node/Rust/Go/Bash functions, class methods, CLI flags, or attributes that do not exist.
   - If an API, syntax, or parameter is uncertain, EXPLICITLY state your uncertainty. Never pretend to know something you do not.
   - NEVER invent synthetic benchmark numbers, non-existent URLs, or fabricated research citations.
   - Do NOT assume any fictional hardware or fake personas. Answer technically, directly, and accurately.

2. PHYSICAL SANDBOX GROUNDING (ACTUAL WORKSPACE FILES):
The following are the exact files currently existing in the active environment ("${envDisplayName}"):
${activeFilesSummary}

${activeFilesContext ? `ACTUAL FILE CONTENTS IN WORKSPACE:\n${activeFilesContext}\n\nWhen modifying or referencing these files, base your answers strictly and verbatim on their actual contents shown above. Do NOT make up different code or pretend files contain things they do not.` : ''}
${ragSection}

3. CHAIN-OF-VERIFICATION (COV) IN INTERNAL REASONING:
   - In your internal <think> reasoning, execute an explicit verification pass:
     • Verify every import and syntax exists in real standard libraries or active workspace.
     • Check function argument types and return contracts.
     • Eliminate any placeholders, stubs, or "TODO" shortcuts.
` : '';

      const systemPrompt = `You are an expert AI software engineer, developer, and technical assistant.
Your answers must be 100% truthful, factual, verifiable, and accurate.
You NEVER make things up. You NEVER fabricate facts, code, APIs, CLI flags, benchmark numbers, or non-existent files.
If information is missing, you state clearly that you do not have that information rather than guessing.
${antiHallucinationSection}
CRITICAL CODE EXECUTION & SANDBOX QUALITY RULES:
The user can spin up a live temporary environment at any time to build, run, and test the files you output. Every piece of code you write must execute flawlessly on the first run.

1. FILE STRUCTURE & EXPLICIT NAMING:
   - ALWAYS specify the exact relative filepath in every markdown code fence header.
     Example: \`\`\`python calculator.py
     Example: \`\`\`python test_calculator.py
     Example: \`\`\`typescript src/index.ts
     Example: \`\`\`json package.json
   - Standard naming conventions:
     • Python entrypoint/logic: main.py, app.py, or <module>.py
     • Python tests: test_<module>.py or tests/test_<module>.py
     • Node / TypeScript: src/<module>.ts, tests in src/<module>.test.ts, entrypoint in index.ts
     • Shell scripts: <tool>.sh with proper #!/usr/bin/env bash header
     • Web apps: index.html, style.css, app.js

2. TEST READINESS & FIRST-PASS RELIABILITY:
   - When writing code, ALWAYS write both the core implementation file AND a corresponding test suite file (e.g. calculator.py + test_calculator.py).
   - Use standard pytest format for Python tests (def test_<feature>(): assert ...).
   - In test files, ensure relative imports match the sandbox root directory (e.g. "from calculator import add" when calculator.py is in the root).
   - Prefer Python standard library modules (os, sys, json, math, re, pathlib, typing, unittest) and standard pytest so tests execute instantly without requiring manual pip installs.
   - If third-party dependencies are required, explicitly provide a requirements.txt or package.json.

3. PRODUCTION IMPLEMENTATION RIGOR:
   - Zero stubbing: NEVER write "...", "# TODO: add implementation", "# rest of code here", or empty pass functions. The code must be 100% complete and operational.
   - Include type hints, parameter docstrings, and robust error handling.
   - Deterministic and testable: Avoid hardcoded external network calls or blocking loops in unit tests; use mocking or self-contained fixtures.`;

      const meshState = useMeshStore.getState();
      const activeEp = meshState.getActiveEndpoint?.() || meshState.candidates.find((c) => c.host === activeHost);
      const apiKey = activeEp?.provider === 'featherless'
        ? meshState.featherlessApiKey
        : meshState.abliteratedApiKey;
      const model = activeEp?.defaultModel;

      await streamChatCompletion({
        host: activeHost,
        port: activePort,
        model,
        apiKey,
        temperature: isAntiHallucination ? 0.0 : 0.7,
        antiHallucination: isAntiHallucination,
        messages: [
          {
            role: 'system',
            content: systemPrompt,
          },
          ...messageHistory,
        ],
        abortSignal: controller.signal,
        callbacks: {
          onToken: (token: string, isReasoning: boolean) => {
            telemetryBridge.recordToken(token);
            if (isReasoning) {
              accumulatedReasoning += token;
            } else {
              accumulatedContent += token;
            }

            const now = Date.now();
            if (now - lastUpdateTime > 40) {
              lastUpdateTime = now;
              set((state) => {
                const sessionMsgs = [
                  ...(state.messages[currentSessionId!] || []),
                ];
                const lastIdx = sessionMsgs.findIndex(
                  (m) => m.id === assistantMsgId
                );
                if (lastIdx !== -1) {
                  sessionMsgs[lastIdx] = {
                    ...sessionMsgs[lastIdx],
                    content: accumulatedContent,
                    reasoning: accumulatedReasoning.trim() || undefined,
                  };
                }
                return {
                  messages: {
                    ...state.messages,
                    [currentSessionId!]: sessionMsgs,
                  },
                };
              });
            }
          },
          onComplete: (finalContent: string, finalReasoning: string) => {
            const completedContent = finalContent || accumulatedContent;
            const groundingReport = evaluateFactualGrounding(
              completedContent,
              activeEnv?.files
            );

            // Extract any files produced in the assistant response and sync with the session environment
            const extractedFiles = extractFilesFromMarkdown(completedContent);

            set((state) => {
              const sessionMsgs = [
                ...(state.messages[currentSessionId!] || []),
              ];
              const lastIdx = sessionMsgs.findIndex(
                (m) => m.id === assistantMsgId
              );
              if (lastIdx !== -1) {
                sessionMsgs[lastIdx] = {
                  ...sessionMsgs[lastIdx],
                  content: completedContent,
                  reasoning:
                    finalReasoning || accumulatedReasoning.trim() || undefined,
                  groundingReport,
                  ragCitations: ragCitations.length ? ragCitations : undefined,
                };
              }

              // Update environment if files were generated
              let nextEnvironments = state.environments;
              const session = state.sessions.find(
                (s) => s.id === currentSessionId
              );
              if (session?.envId && extractedFiles.length > 0) {
                const targetEnv = state.environments[session.envId];
                if (targetEnv) {
                  const updatedFiles = { ...targetEnv.files };
                  for (const f of extractedFiles) {
                    updatedFiles[f.path] = f;
                    markFileDirty(session.envId, f.path);
                  }
                  nextEnvironments = {
                    ...state.environments,
                    [session.envId]: {
                      ...targetEnv,
                      files: updatedFiles,
                      updatedAt: Date.now(),
                    },
                  };
                }
              }

              return {
                messages: {
                  ...state.messages,
                  [currentSessionId!]: sessionMsgs,
                },
                environments: nextEnvironments,
                isStreaming: false,
                activeAbortController: null,
              };
            });
            void get().flushSave();
          },
          onError: (error: Error) => {
            console.error('Streaming error in ChatStore:', error);
            set({ isStreaming: false, activeAbortController: null });
          },
        },
      });
    } catch (error) {
      console.error('Send message failure:', error);
      set({ isStreaming: false, activeAbortController: null });
    }
  },

  stopStreaming: () => {
    const controller = get().activeAbortController;
    if (controller) {
      controller.abort();
    }
    set({ isStreaming: false, activeAbortController: null });
    void get().flushSave();
  },

  loadFromStorage: async () => {
    try {
      const data = await AsyncStorage.getItem(STORAGE_KEY);
      if (data) {
        const parsed = JSON.parse(data);
        let sessions: ChatSession[] = parsed.sessions || [];
        const messages = parsed.messages || {};
        const environments: Record<string, SessionEnvironment> =
          parsed.environments || {};

        // Migrate any legacy sessions missing envId or missing environment record
        let migrated = false;
        sessions = sessions.map((s) => {
          if (!s.envId) {
            migrated = true;
            const newEnv = createInitialEnvironment(s.id);
            environments[newEnv.id] = newEnv;
            return { ...s, envId: newEnv.id };
          }
          if (!environments[s.envId]) {
            migrated = true;
            environments[s.envId] = createInitialEnvironment(s.id);
          }
          return s;
        });

        set({
          sessions,
          messages,
          environments,
          activeSessionId: sessions.length > 0 ? sessions[0].id : null,
        });

        for (const env of Object.values(environments)) {
          markEnvAllDirty(env.id, Object.keys(env.files));
        }

        if (migrated) {
          persistDirty = true;
          await get().saveToStorage();
        }
      } else {
        // Initialize with default welcome session & environment
        const welcomeId = 'session_welcome';
        const welcomeEnv = createInitialEnvironment(welcomeId);
        welcomeEnv.name = 'sandbox-welcome';
        welcomeEnv.files = {
          'README.md': {
            path: 'README.md',
            content: `# DGX Spark GB10 Sandbox Environment\n\nInitialized sovereign environment directly mapped to DGX Spark.\n- Host: 192.168.4.103:8000 (GB10 Blackwell FP8)\n- Model: qwen-abliterated\n\nGenerated files from this conversation will automatically appear here.\nTap 'Download ZIP' in the environment menu to export.\n`,
            language: 'markdown',
            updatedAt: Date.now(),
            sizeBytes: 310,
          },
          'spark-info.json': {
            path: 'spark-info.json',
            content: JSON.stringify(
              {
                system: 'NVIDIA DGX Spark',
                architecture: 'GB10 Blackwell',
                contextWindow: 65536,
                sandboxIsolation: 'Per-Conversation Ephemeral',
                exportFormat: 'PKZIP 2.0',
              },
              null,
              2
            ),
            language: 'json',
            updatedAt: Date.now(),
            sizeBytes: 215,
          },
        };

        const welcomeSession: ChatSession = {
          id: welcomeId,
          title: 'DGX Spark Initialization',
          envId: welcomeEnv.id,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        };

        const welcomeMsgs: Message[] = [
          {
            id: 'msg_w1',
            role: 'assistant',
            content: `### ⚡ Sovereign Spark Mobile Client Initialized

Directly linked to on-premise **NVIDIA DGX Spark** (Blackwell GB10 GPU).
- **Primary Endpoint**: \`http://192.168.4.103:8000\`
- **Mesh Fallback**: \`http://100.94.45.77:8000\` (Tailscale)
- **Model**: \`qwen-abliterated\` (FP8 Tensor Cores)
- **Dedicated Sandbox**: Each conversation now has an isolated workspace environment (\`${welcomeEnv.name}\`). Any code files generated are saved in real-time and ready to download as a ZIP!

No telemetry. No rate limits. Uncensored local intelligence. Ask any question or tap a quick chip below!`,
            reasoning: `Initialized secure socket connection with DGX Spark cluster.
Verified NVLink 5 memory interconnect at 1.2 TB/s.
Ephemeral sandbox created: ${welcomeEnv.id}.
Ready for streaming completions.`,
            timestamp: Date.now(),
          },
        ];

        set({
          sessions: [welcomeSession],
          environments: { [welcomeEnv.id]: welcomeEnv },
          activeSessionId: welcomeId,
          messages: { [welcomeId]: welcomeMsgs },
        });

        markEnvAllDirty(welcomeEnv.id, Object.keys(welcomeEnv.files));
        persistDirty = true;
        await get().saveToStorage();
      }
    } catch (e) {
      console.error('Failed to load chat history', e);
    }
  },

  saveToStorage: async () => {
    if (!persistDirty) return;
    persistDirty = false;
    if (saveTimer) {
      clearTimeout(saveTimer);
      saveTimer = null;
    }
    try {
      const { sessions, messages, environments } = get();
      await AsyncStorage.setItem(
        STORAGE_KEY,
        JSON.stringify({ sessions, messages, environments })
      );
    } catch (e) {
      persistDirty = true;
      console.error('Failed to persist chat history', e);
    }
  },

  flushSave: async () => {
    persistDirty = true;
    await get().saveToStorage();
  },
}));

// Wire Multi-Agent Swarm events directly into Chat store
const swarmFileBuf: { envId: string; path: string; content: string; language?: string }[] = [];
let swarmFileTimer: ReturnType<typeof setTimeout> | null = null;

function flushSwarmFileBuf() {
  swarmFileTimer = null;
  if (!swarmFileBuf.length) return;
  const byEnv = new Map<string, typeof swarmFileBuf>();
  while (swarmFileBuf.length) {
    const item = swarmFileBuf.shift()!;
    const list = byEnv.get(item.envId) || [];
    list.push(item);
    byEnv.set(item.envId, list);
  }
  const store = useChatStore.getState();
  for (const [envId, files] of byEnv) {
    store.addOrUpdateFiles(envId, files);
  }
}

registerSwarmListeners(
  (swarm) => useChatStore.getState().updateLastAssistantMessageSwarm(swarm),
  (envId, file) => {
    swarmFileBuf.push({
      envId,
      path: file.path,
      content: file.content,
      language: file.language,
    });
    if (!swarmFileTimer) {
      swarmFileTimer = setTimeout(flushSwarmFileBuf, 50);
    }
  },
  async () => {
    try {
      flushSwarmFileBuf();
      await useChatStore.getState().flushSave();
      const { useSandboxStore } = await import('./useSandboxStore');
      await useSandboxStore.getState().materializeActiveEnv();
      await useSandboxStore.getState().runTestsForEnv();
    } catch (err) {
      console.warn('[Swarm] Sandbox execution callback warning:', err);
    }
  }
);

if (typeof window !== 'undefined') {
  window.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'hidden') {
      void useChatStore.getState().flushSave();
    }
  });
  window.addEventListener('beforeunload', () => {
    void useChatStore.getState().flushSave();
  });
}
